---
kind: pipeline
type: docker
name: docker

steps:
- name: build_mod
  image: debian:latest
  commands:
      - /usr/bin/apt update
      - /usr/bin/apt install -y zip jq libxml2-utils
      - /bin/bash bin/build.sh
- name: deploy
  image: drillster/drone-rsync
  settings:
    hosts: [ "127.0.0.1" ]
    user: 
      from_secret: ssh_user
    source: dist/*
    target: 
      from_secret: ssh_path
    recursive: true
    delete: true
    key:
      from_secret: ssh_key
- name: push commit
  image: appleboy/drone-git-push
  settings:
    branch: master
    remote: git@github.com:aoi/FS22_Impress185VCAoiEdition
    force: false
    commit: true

  